/**
 * @fileoverview gRPC-Web generated client stub for flashcontrol
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.0
// source: flashControl.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.flashcontrol = require('./flashControl_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.flashcontrol.FlashControlClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.flashcontrol.FlashControlPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.flashcontrol.PhotoRequest,
 *   !proto.flashcontrol.PhotoResponse>}
 */
const methodDescriptor_FlashControl_TakePhoto = new grpc.web.MethodDescriptor(
  '/flashcontrol.FlashControl/TakePhoto',
  grpc.web.MethodType.UNARY,
  proto.flashcontrol.PhotoRequest,
  proto.flashcontrol.PhotoResponse,
  /**
   * @param {!proto.flashcontrol.PhotoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.flashcontrol.PhotoResponse.deserializeBinary
);


/**
 * @param {!proto.flashcontrol.PhotoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.flashcontrol.PhotoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.flashcontrol.PhotoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.flashcontrol.FlashControlClient.prototype.takePhoto =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/flashcontrol.FlashControl/TakePhoto',
      request,
      metadata || {},
      methodDescriptor_FlashControl_TakePhoto,
      callback);
};


/**
 * @param {!proto.flashcontrol.PhotoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.flashcontrol.PhotoResponse>}
 *     Promise that resolves to the response
 */
proto.flashcontrol.FlashControlPromiseClient.prototype.takePhoto =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/flashcontrol.FlashControl/TakePhoto',
      request,
      metadata || {},
      methodDescriptor_FlashControl_TakePhoto);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.flashcontrol.PhotoPathResponse>}
 */
const methodDescriptor_FlashControl_TakePhotoWithNativeCamera = new grpc.web.MethodDescriptor(
  '/flashcontrol.FlashControl/TakePhotoWithNativeCamera',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.flashcontrol.PhotoPathResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.flashcontrol.PhotoPathResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.flashcontrol.PhotoPathResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.flashcontrol.PhotoPathResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.flashcontrol.FlashControlClient.prototype.takePhotoWithNativeCamera =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/flashcontrol.FlashControl/TakePhotoWithNativeCamera',
      request,
      metadata || {},
      methodDescriptor_FlashControl_TakePhotoWithNativeCamera,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.flashcontrol.PhotoPathResponse>}
 *     Promise that resolves to the response
 */
proto.flashcontrol.FlashControlPromiseClient.prototype.takePhotoWithNativeCamera =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/flashcontrol.FlashControl/TakePhotoWithNativeCamera',
      request,
      metadata || {},
      methodDescriptor_FlashControl_TakePhotoWithNativeCamera);
};


module.exports = proto.flashcontrol;

